name: Check product locales
on:
  schedule:
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Check product locales
        run: |
          python .github/scripts/check_product_locales.py --product focus
