name: Import strings
on:
  workflow_dispatch:
    inputs:
      type:
        description: Type of update (standard, nofile, matchid)
        required: true
        default: "standard"

jobs:
  build:
    runs-on: macos-12
    strategy:
      max-parallel: 4
      matrix:
        xcode: ["13.4"]
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          path: "l10n_repo"
      - name: Clone main code repository
        uses: actions/checkout@v3
        with:
          repository: "mozilla-mobile/focus-ios"
          path: "code_repo"
      - name: Select Xcode ${{ matrix.xcode }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          pip install -r l10n_repo/.github/scripts/requirements.txt
      - name: Run checkout script
        run: |
          (cd code_repo && ./checkout.sh)
      - name: Extract strings
        run: |
          (cd code_repo && ./tools/export-strings.sh)

          # Copy strings to other locales
          cp code_repo/focusios-l10n/en-US/*.xliff l10n_repo/en-US/
          python l10n_repo/.github/scripts/update_other_locales.py --reference en-US --path l10n_repo --type "${{ github.event.inputs.type }}"
      - name: Get the current date for PR title
        run: echo "current_date=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@v4
        with:
          path: "l10n_repo"
          commit-message: "Extract new strings (${{ env.current_date }})"
          branch: l10n_automation
          delete-branch: true
          title: "Extract new strings (${{ env.current_date }})"
